version: '3.8'

services:
  redis:
    image: redis:7.0-alpine
    container_name: document_redis
    ports:
      - "6379:6379"
    networks:
      - document_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:6.0
    container_name: document_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: app_db
    networks:
      - document_network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/app_db --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  minio:
    image: minio/minio
    container_name: document_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    networks:
      - document_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

networks:
  document_network:
    driver: bridge